from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1209, 852)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 40, 391, 331))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 20, 391, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.randomMatrixLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.randomMatrixLayout.setContentsMargins(0, 0, 0, 0)
        self.randomMatrixLayout.setObjectName("randomMatrixLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.rowsSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.rowsSpinBox.setGeometry(QtCore.QRect(140, 10, 42, 22))
        self.rowsSpinBox.setObjectName("rowsSpinBox")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 10, 55, 16))
        self.label_2.setObjectName("label_2")
        self.columnSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.columnSpinBox.setGeometry(QtCore.QRect(200, 10, 42, 22))
        self.columnSpinBox.setObjectName("columnSpinBox")
        self.generateImageButton = QtWidgets.QPushButton(self.centralwidget)
        self.generateImageButton.setGeometry(QtCore.QRect(262, 10, 131, 28))
        self.generateImageButton.setObjectName("generateImageButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(410, 40, 391, 331))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 20, 391, 311))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.bayerLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.bayerLayout.setContentsMargins(0, 0, 0, 0)
        self.bayerLayout.setObjectName("bayerLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(810, 40, 391, 331))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 20, 391, 311))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.interpolatedImageLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.interpolatedImageLayout.setContentsMargins(0, 0, 0, 0)
        self.interpolatedImageLayout.setObjectName("interpolatedImageLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 460, 391, 331))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 20, 391, 311))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.hueLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.hueLayout.setContentsMargins(0, 0, 0, 0)
        self.hueLayout.setObjectName("hueLayout")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(410, 460, 391, 331))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_5)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(0, 20, 391, 311))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.saturationLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.saturationLayout.setContentsMargins(0, 0, 0, 0)
        self.saturationLayout.setObjectName("saturationLayout")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(810, 460, 391, 331))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.groupBox_6)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(0, 20, 391, 311))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.valueLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.valueLayout.setContentsMargins(0, 0, 0, 0)
        self.valueLayout.setObjectName("valueLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(450, 390, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1209, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Random Matrix Image"))
        self.label.setText(_translate("MainWindow", "Dimensions:"))
        self.label_2.setText(_translate("MainWindow", "x"))
        self.generateImageButton.setText(_translate("MainWindow", "Generate Image"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Bayer Filter"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Interpolated Image"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Hue Channel"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Saturation Channel"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Value Channel"))
        self.label_3.setText(_translate("MainWindow", "Color Space"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
